version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: "weekly"
    groups:
      crates-io:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
